### ISSUE TITLE
compilation broken on >=glibc-2.25

### ISSUE THREAD

**Issue by ultrabug** [cloudius-systems/dpdk#3]
Users trying to compile scylladb with dpdk enabled will fail if their version of glibc is >=2.25 with the following error:

```
dpdk/lib/librte_eal/linuxapp/eal/eal_pci_uio.c:134:8: error: implicit declaration of function ‘makedev’ [-Werror=implicit-function-declaration]
  dev = makedev(major, minor);
        ^
dpdk/lib/librte_eal/linuxapp/eal/eal_pci_uio.c:134:2: error: nested extern declaration of ‘makedev’ [-Werror=nested-externs]
  dev = makedev(major, minor);
  ^
cc1: all warnings being treated as errors
```

This is due to the following change in glibc:

```
* The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.  This
  means that in a future release, the macros “major”, “minor”, and “makedev”
  will only be available from <sys/sysmacros.h>.
```

The fix is to `#include <sys/sysmacros.h>` in the `dpdk/lib/librte_eal/linuxapp/eal/eal_pci_uio.c` file :)

I'm not submitting a PR because I've seen that you plan on upgrading your copy of dpdk wrt gcc-6 support, but if you want one just ask ;)

Meanwhile I will maintain a patch on Gentoo packaging for this until this issue is closed.

**Comment by ultrabug** [comment]
For full reference, I found this out thanks to this bug report : https://sourceware.org/bugzilla/show_bug.cgi?id=19239

**Comment by avikivity** [comment]
Do you know if upstream dpdk has this bug fixed? If so, which version? If not, I suggest patching upstream dpdk.

We already carry local patches, see branch local-17.02, so it's not a problem to carry more.

**Comment by ultrabug** [comment]
The answer is yes, with the same fix I'm doing:

```
* commit 9256eed78a2ddd54c363241568a744ff65051f13
| Author: Jerin Jacob <jerin.jacob@caviumnetworks.com>
| Date:   Mon Apr 3 14:05:14 2017 +0530
| 
|     eal/linux: fix build with glibc 2.25
|     
|     glibc 2.25 is warning about if applications depend on
|     sys/types.h for makedev macro, it expects to be included
|     from <sys/sysmacros.h>
|     
|     Found this error while testing with GCC 6.3.1 on archlinux.
|     
|     lib/librte_eal/linuxapp/eal/eal_pci_uio.c: In function ‘pci_mknod_uio_dev’:
|     lib/librte_eal/linuxapp/eal/eal_pci_uio.c:134:13:
|     error: In the GNU C Library, "makedev" is defined
|     by <sys/sysmacros.h>. For historical compatibility, it is
|     currently defined by <sys/types.h> as well, but we plan to
|     remove this soon. To use "makedev", include <sys/sysmacros.h>
|     directly. If you did not intend to use a system-defined macro
|     "makedev", you should undefine it after including <sys/types.h>. [-Werror]
|      dev = makedev(major, minor);
|                  ^~~~~~~~~~~~~~~~~
|     
|     Signed-off-by: Jerin Jacob <jerin.jacob@caviumnetworks.com>
| ---
|  lib/librte_eal/linuxapp/eal/eal_pci_uio.c | 1 +
|  1 file changed, 1 insertion(+)
| 
| diff --git a/lib/librte_eal/linuxapp/eal/eal_pci_uio.c b/lib/librte_eal/linuxapp/eal/eal_pci_uio.c
| index 20a4a665e..fa10329fd 100644
| --- a/lib/librte_eal/linuxapp/eal/eal_pci_uio.c
| +++ b/lib/librte_eal/linuxapp/eal/eal_pci_uio.c
| @@ -38,6 +38,7 @@
|  #include <inttypes.h>
|  #include <sys/stat.h>
|  #include <sys/mman.h>
| +#include <sys/sysmacros.h>
|  #include <linux/pci_regs.h>
|  
|  #if defined(RTE_ARCH_X86)
|
```

**Comment by avikivity** [comment]
Fixed by 82e4f87034d195bf4e41d060d738e773ba5d475b

**Comment by ultrabug** [comment]
@avikivity I see that this is still not included on 2.0.2, is there any blocker about that please ?

**Comment by avikivity** [comment]
No blocker, I can backport it.

**Comment by ultrabug** [comment]
That would be great thanks.

**Comment by avikivity** [comment]
It's already committed (scylladb/scylla@7bef696ee5232bada8ec0e1007f12e8dbb81ba70)

**Comment by ultrabug** [comment]
Thanks a lot mate
